name: ibus-uniemoji
version: 0.6.0
release: 1
source:
    - https://github.com/salty-horse/ibus-uniemoji/archive/v0.6.0.tar.gz: 295a698e6065366d06d54786a272ac69417f709053cfe32bf42520dc5311052a
license: GPL-3.0-or-later
component: desktop.core
summary: A simple input method for ibus that allows you to enter unicode emoji and other symbols by name
description: |
    A simple input method for ibus that allows you to enter unicode emoji and other symbols by name
build: |
    %make PREFIX=/usr
install: |
    %make_install
rundeps:
    - python-levenshtein
    - python3
    - ibus
