name: cuppa
version: 0.0.1
release: 1
source:
    - git|https://github.com/DataDrake/cuppa: a171371b975d03ec86a297e8117a4c494a1d95d0
license: Apache-2.0
component: programming.tools
summary: Comprehensive Upstream Provider Polling Assistant
description: |
    As a package maintainer, it's a challenging task to keep track of every new release of a piece of software. Usually this involves subscribing to mailing lists, signing up for notifications from FOSS portals like Github, or even subscribing to news sites. For a distro, this might also mean a repeated effort amongst its package maintainers. The inefficiency and time requirements of such an approach is inevitable. This has led several distros to create their own upstream tracking platforms to automate the process of tracking upstream releases. However, these platforms are often distro specific, leading to further duplication of effort between distros.
build: |
    %make
install: |
    %make_install
builddeps:
    - golang
networking: yes
