name: guayadeque
version: 0.4.5
release: 1
source:
    - https://github.com/anonbeat/guayadeque/archive/v0.4.5.tar.gz: a0c4eb9f0eb42e701880a1d196e847d68a3b443716a6240389fbfafef3f5d19c
license: GPL-3.0-or-later
component: multimedia.audio
summary: Music management program based on Gstreamer.
description: |
    Guayadeque is a music management program designed for all music enthusiasts. It is Full Featured Linux media player that can easily manage large collections and uses the Gstreamer media framework.
setup: |
    cd "$workdir"
    ./buildt
    %cmake -DCMAKE_CXX_STANDARD="11" -DwxWidgets_wxrc_EXECUTABLE='/usr/bin/wxrc-3.0' -DwxWidgets_CONFIG_EXECUTABLE='/usr/bin/wx-config' -DwxWidgets_INCLUDE_DIRS='/usr/include/wx-3.0/'
build: |
    %make
install: |
    %make_install
builddeps:
    - gettext
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-tag-1.0)
    - pkgconfig(sqlite3)
    - pkgconfig(libcurl)
    - pkgconfig(taglib)
    - pkgconfig(dbus-1)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gio-2.0)
    - pkgconfig(libgpod-1.0)
    - pkgconfig(wxsqlite3)
    - wxwidgets-devel
